[BE] Homework 5
ArtMan-8/aws-nodejs-BE pull request #2
Opened 2022-01-04 10:54 UTC by ArtMan-8

resolve https://github.com/ArtMan-8/aws-nodejs/issues/5
resolve https://github.com/ArtMan-8/aws-nodejs/issues/6

2022-01-10 09:11 UTC, maxm-dev requested changes

2022-01-10 09:11 UTC, maxm-dev commented on product-service/src/functions/addProduct/handler.ts
> +			('${title}', '${description}', '${price}')
As we discussed on common meeting, this is a SQL injection vulnerability. Use [parameterized query](https://node-postgres.com/features/queries) instead, please.

2022-01-10 09:34 UTC, ArtMan-8 commented on product-service/openapi.yml
> +openapi: 3.0.0
Да, на основе `documentation.ts` и `index.ts` в лямбдах.

2022-01-11 16:44 UTC, ArtMan-8 commented on product-service/src/functions/addProduct/handler.ts
> +			('${title}', '${description}', '${price}')
Просмотрел,
в одном месте поправил, а в этом нет.

2022-01-11 17:15 UTC, maxm-dev approved these changes

2022-01-11 18:34 UTC, merged